name    'davidcollom-serf'
version '0.1.3'
source 'https://github.com/davidcollom/puppet-serf'
author 'David Collom'
license 'MIT'
summary ''
description 'The Serf module installs, configures, and manages a Serf agent.'
project_page 'https://github.com/davidcollom/puppet-serf'
dependency 'puppetlabs/stdlib'
